### PR TITLE
Add doctrine cache flush

### PR DESCRIPTION
**Pull request by guilherme-santos**
What do you think add new commands to clear doctrine cache?

### CODE REVIEW

**Comment by juriansluiman** [comment]
Awesome! Will test it later, but I agree it sounds as a sane add-on :)

**Comment by juriansluiman** [comment]
I have tested it now, looks like it's all running fine. However, I think we could help users with the following:
1. Clear all by default. If you don't provide an additional argument, doing nothing isn't what I would expect. Clearing all by default is the same as the Doctrine CLI works now
2. If a user specifies what type of cache he want to flush, I'd print this explicitly in the results
3. The Doctrine CLI is `./doctrine clear-cache`, Soflomo\Cache often uses `--clear-*` but your CLI parameter is `--doctrine-flush`. I would change this to `--clear-doctrine`. So it would say "cache clear doctrine" which sounds more natural.

The command route would then look like this:

```
cache --clear-doctrine [--query|-q] [--result|-r] [--metadata|-m] [--hydration|-h]
```

And the php action:

``` php
public function flushAction()
{
    $console = $this->getConsole();
    $config  = $this->getObjectManager()->getConfiguration();

    // All is true when no other params are given
    $all = !$this->params('query')     && !$this->params('q')
        && !$this->params('result')    && !$this->params('r')
        && !$this->params('metadata')  && !$this->params('m')
        && !$this->params('hydration') && !$this->params('h');

    if ($all || $this->params('query') || $this->params('q')) {
        $config->getQueryCacheImpl()->flushAll();
        if (!$all) {
            $console->writeLine('Doctrine query cache flushed');
        }
    }
    if ($all || $this->params('result') || $this->params('r')) {
        $config->getResultCacheImpl()->flushAll();
        if (!$all) {
            $console->writeLine('Doctrine result cache flushed');
        }
    }
    if ($all || $this->params('metadata') || $this->params('m')) {
        $config->getMetadataCacheImpl()->flushAll();
        if (!$all) {
            $console->writeLine('Doctrine metadata cache flushed');
        }
    }
    if ($all || $this->params('hydration') || $this->params('h')) {
        $config->getHydrationCacheImpl()->flushAll();
        if (!$all) {
            $console->writeLine('Doctrine hydration cache flushed');
        }
    }

    if ($all) {
        $console->writeLine('All Doctrine caches are flushed');
    }
}
```

Could you update your code accordingly?

**Comment by guilherme-santos** [comment]
Of course, I'm going to update!

**Comment by guilherme-santos** [comment]
I made improvements that you suggest!

**Comment by juriansluiman** [comment]
Thanks @guilherme-santos. The only thing I forgot in the last comment is to adjust the help text as well. Could you format the console usage part like I did [here](https://github.com/guilherme-santos/Cache/blob/master/Module.php#L73-L81)? Notice you can remove the `--all` from [the doctrine usage](https://github.com/guilherme-santos/Cache/blob/master/Module.php#L101-L106) as well.

Then I can merge it. I will wait until I finished the opcode caching as well, then I will tag the module for v0.2.0

**Comment by guilherme-santos** [comment]
Here you go!

**Comment by juriansluiman** [comment]
:shipit: Thank you @guilherme-santos

**Pull request merged**
